export class Reportecliente {
    
    USR_ID?;
    USR_USERNAME?;
    USR_CORREO?;
    USR_NOMBRECOMPLETO?;
    USR_PASSWORD?;
    USR_TIPOUSUARIO?;
    USR_IDPERFIL?;

    REP_CLI_ID?;
    REP_ID_CLI?;
    REP_FECHA?;
    REP_VISITAS?;
    REP_ASESORIAS?;
    REP_PROPUESTAS?;
    REP_ACCIDENTES?;
    REP_PROFESIONAL?;
    REP_CAPACITACIONES?;

}